version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  mongodb:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./mongodb
  front-end:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./front-end
    volumes:
      - /app/node_modules
      - ./front-end:/app
  back-end:
    build:
      dockerfile: Dockerfile.dev
      context: './back-end'
    volumes:
      - /app/node_modules
      - ./back-end:/app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://3.35.20.27:9080/dropcare-cnuh
      - SECRET_KEY=MySecretKey
      - JWT_SECRET=asdasdasd
      - INFLUX_URL=http://db.doctorsfab.com:8086